export const APPEAR_LOADING = 'APPEAR_LOADING'
export const HIDE_LOADING = 'HIDE_LOADING'
export const APPEAR_SMALL_LOADING = 'APPEAR_SMALL_LOADING'
export const HIDE_SMALL_LOADING = 'HIDE_SMALL_LOADING'