export const MESSAGE_APPEAR = 'MESSAGE_APPEAR'
export const MESSAGE_DISAPPEAR = 'MESSAGE_DISAPPEAR'
export const MESSAGE_ALERT_APPEAR = 'MESSAGE_ALERT_APPEAR'
export const MESSAGE_ALERT_DISAPPEAR = 'MESSAGE_ALERT_DISAPPEAR'