export const GET_USER_LOGIN = 'GET_USER_LOGIN'
export const MESSAGE_ERROR_SIGN_IN = 'MESSAGE_ERROR_SIGN_IN'
export const MESSAGE_APPEAR = 'MESSAGE_APPEAR'
export const MESSAGE_DISAPPEAR = 'MESSAGE_DISAPPEAR'